modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Mrthomas20121-Mods/tinkersweaponry/issues"

[[mods]]
modId="tinkersweaponry"
version="1.20.1-0.0.4"
displayName="Tinkers' Weaponry"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkersweaponry"
#logoFile="tinkers_reforged_logo.png"
authors="Mrthomas20121"
description='''
Add Thermal Compat to Tinkers
'''

[[dependencies.tinkersweaponry]]
	modId = "forge"
	mandatory = true
	versionRange = "[47.2.6,)"
	ordering = "NONE"
	side = "BOTH"
[[dependencies.tinkersweaponry]]
	modId = "tconstruct"
	mandatory = true
	versionRange = "[3.9.2.37,)"
	ordering = "AFTER"
	side = "BOTH"